# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the mysql  gem is defined in your Gemfile
#   gem 'mysql2'
#
development:
  host: 127.0.0.1
  adapter: mysql2
  encoding: utf8
  database: dev-db
  pool: 5
  timeout: 5000
  password: hakunamatata
  strict: false

test:
  host: 127.0.0.1
  adapter: mysql2
  encoding: utf8
  database: test-db
  pool: 5
  timeout: 5000
  password: hakunamatata
  strict: false
  
production:
  host: 127.0.0.1
  adapter: mysql2
  encoding: utf8
  database: prod-db
  pool: 5
  timeout: 5000
  password: hakunamatata
  strict: false







