# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Commodity_List = [
  ["1","Live animals"],
["2","Meat and edible meat offal"],
["3","Fish and crustaceans, molluscs and other aquatic invertebrates"],
["4","Dairy produce; birds' eggs; natural honey; edible products of animal origin, not elsewhere specified or included"],
["5","Products of animal origin, not elsewhere specified or included"],
["6","Live trees and other plants; bulbs, roots and the like; cut flowers and ornamental foliage"],
["7","Edible vegetables and certain roots and tubers"],
["8","Edible fruit and nuts; peel of citrus fruit or melons"],
["9","Coffee, tea, matÃƒÂ© and spices"],
["10","Cereals"],
["11","Products of the milling industry; malt; starches; inulin; wheat gluten"],
["12","Oil seeds and oleaginous fruits; miscellaneous grains,seeds and fruit; industrial or medicinal plants; straw and fodder"],
["13","Lac; gums, resins and other vegetable saps and extracts"],
["14","Vegetable plaiting materials; vegetable products not elsewhere specified or included"],
["15","Animal or vegetable fats and oils and their cleavage products; prepared edible fats; animal or vegetable waxes"],
["16","Preparations of meat, of fish or of crustaceans, molluscs or other aquatic invertebrates"],
["17","Sugars and sugar confectionery"],
["18","Cocoa and cocoa preparations"],
["19","Preparations of cereals, flour, starch or milk; pastrycooks' products"],
["20","Preparations of vegetables, fruit, nuts or other parts of plants"],
["21","Miscellaneous edible preparations"],
["22","Beverages, spirits and vinegar"],
["23","Residues and waste from the food industries; prepared animal fodder"],
["24","Tobacco and manufactured tobacco substitutes"],
["25","Salt; sulphur; earths and stone; plastering materials, lime and cement"],
["26","Ores, slag and ash"],
["27","Mineral fuels, mineral oils and products of their distillation; bituminous substances; mineral waxes"],
["28","Inorganic chemicals; organic or inorganic compounds of precious metals, of rareearth metals, of radioactive elements or of isotopes"],
["29","Organic chemicals"],
["30","Pharmaceutical products"],
["31","Fertilisers"],
["32","Tanning or dyeing extracts; tannins and their derivatives; dyes, pigments and other colouring matter; paints and varnishes; putty and other mastics; inks"],
["33","Essential oils and resinoids; perfumery, cosmetic or toilet preparations"],
["34","Soap, organic surfaceactive agents, washing preparations, lubricating preparations, artificial waxes, prepared waxes, polishing or scouring preparations, candles and similar articles, modelling pastes, Ã¢â‚¬Å“dental waxesÃ¢â‚¬Â and dental preparations with a basis of plaster"],
["35","Albuminoidal substances; modified starches; glues; enzymes"],
["36","Explosives; pyrotechnic products; matches; pyrophoric alloys; certain combustible preparations"],
["37","Photographic or cinematographic goods"],
["38","Miscellaneous chemical products"],
["39","Plastics and articles thereof"],
["40","Rubber and articles thereof"],
["41","Raw hides and skins (other than furskins) and leather"],
["42","Articles of leather; saddlery and harness; travel goods, handbags and similar containers; articles of animal gut (other than silkworm gut)"],
["43","Furskins and artificial fur; manufactures thereof"],
["44","Wood and articles of wood; wood charcoal"],
["45","Cork and articles of cork"],
["46","Manufactures of straw, of esparto or of other plaiting materials; basketware and wickerwork"],
["47","Pulp of wood or of other fibrous cellulosic material; recovered (waste and scrap) paper or paperboard"],
["48","Paper and paperboard; articles of paper pulp, of paper or of paperboard"],
["49","Printed books, newspapers, pictures and other products of the printing industry; manuscripts, typescripts and plans"],
["50","Silk"],
["51","Wool, fine or coarse animal hair; horsehair yarn and woven fabric"],
["52","Cotton"],
["53","Other vegetable textile fibres; paper yarn and woven fabrics of paper yarn"],
["54","Manmade filaments; strip and the like of manmade textile materials"],
["55","Manmade staple fibres"],
["56","Wadding, felt and nonwovens; special yarns; twine, cordage, ropes and cables and articles thereof"],
["57","Carpets and other textile floor coverings"],
["58","Special woven fabrics; tufted textile fabrics; lace; tapestries; trimmings; embroidery"],
["59","Impregnated, coated, covered or laminated textile fabrics; textile articles of a kind suitable for industrial use"],
["60","Knitted or crocheted fabrics"],
["61","Articles of apparel and clothing accessories, knitted or crocheted"],
["62","Articles of apparel and clothing accessories,not knitted or crocheted"],
["63","Other made up textile articles; sets; worn clothing and worn textile articles; rags"],
["64","Footwear, gaiters and the like; parts of such articles"],
["65","Headgear and parts thereof"],
["66","Umbrellas, sun umbrellas, walkingsticks, seatsticks, whips, ridingcrops and parts thereof"],
["67","Prepared feathers and down and articles made of feathers or of down; artificial flowers; articles of human hair"],
["68","Articles of stone, plaster, cement, asbestos, mica or similar materials"],
["69","Ceramic products"],
["70","Glass and glassware"],
["71","Natural or cultured pearls, precious or semiprecious stones, precious metals, metals clad with precious metal, and articles thereof; imitation jewellery; coin"],
["72","Iron and steel"],
["73","Articles of iron or steel"],
["74","Copper and articles thereof"],
["75","Nickel and articles thereof"],
["76","Aluminium and articles thereof"],
["77","(Reserved for possible future use in the Harmonized System)"],
["78","Lead and articles thereof"],
["79","Zinc and articles thereof"],
["80","Tin and articles thereof"],
["81","Other base metals; cermets; articles thereof"],
["82","Tools, implements, cutlery, spoons and forks, of base metal; parts thereof of base metal"],
["83","Miscellaneous articles of base metal"],
["84","Nuclear reactors, boilers, machinery and mechanical appliances; parts thereof"],
["85","Electrical machinery and equipment and parts thereof; sound recorders and reproducers, television image and sound recorders and reproducers, and parts and accessories of such articles"],
["86","Railway or tramway locomotives, rollingstock and parts thereof; railway or tramway track fixtures and fittings and parts thereof; mechanical (including electromechanical) traffic signalling equipment of all kinds"],
["87","Vehicles other than railway or tramway rollingstock, and parts and accessories thereof"],
["88","Aircraft, spacecraft, and parts thereof"],
["89","Ships, boats and floating structures"],
["90","Optical, photographic, cinematographic, measuring, checking, precision, medical or surgical instruments and apparatus; parts and accessories thereof"],
["91","Clocks and watches and parts thereof"],
["92","Musical instruments; parts and accessories of such articles"],
["93","Arms and ammunition; parts and accessories thereof"],
["94","Furniture; bedding, mattresses, mattress supports, cushions and similar stuffed furnishings; lamps and lighting fittings, not elsewhere specified or included; illuminated signs, illuminated nameplates and the like; prefabricated buildings"],
["95","Toys, games and sports requisites; parts and accessories thereof"],
["96","Miscellaneous manufactured articles"]

]


Country_List = [
  ["899","NR"],
  ["0","World"],
    ["4","Afghanistan"],
    ["8","Albania"],
    ["10","Antarctica"],
    ["12","Algeria"],
    ["16","American Samoa"],
    ["20","Andorra"],
    ["24","Angola"],
    ["28","Antigua and Barbuda"],
    ["31","Azerbaijan"],
    ["32","Argentina"],
    ["36","Australia"],
    ["40","Austria"],
    ["44","Bahamas"],
    ["48","Bahrain"],
    ["50","Bangladesh"],
    ["51","Armenia"],
    ["52","Barbados"],
    ["56","Belgium"],
    ["58","Belgium-Luxembourg"],
    ["60","Bermuda"],
    ["64","Bhutan"],
    ["68","Bolivia (Plurinational State of)"],
    ["70","Bosnia Herzegovina"],
    ["72","Botswana"],
    ["74","Bouvet Island"],
    ["76","Brazil"],
    ["80","Br. Antarctic Terr."],
    ["84","Belize"],
    ["86","Br. Indian Ocean Terr."],
    ["90","Solomon Isds"],
    ["92","Br. Virgin Isds"],
    ["96","Brunei Darussalam"],
    ["100","Bulgaria"],
    ["104","Myanmar"],
    ["108","Burundi"],
    ["112","Belarus"],
    ["116","Cambodia"],
    ["120","Cameroon"],
    ["124","Canada"],
    ["132","Cabo Verde"],
    ["136","Cayman Isds"],
    ["140","Central African Rep."],
    ["144","Sri Lanka"],
    ["148","Chad"],
    ["152","Chile"],
    ["156","China"],
    ["162","Christmas Isds"],
    ["166","Cocos Isds"],
    ["170","Colombia"],
    ["174","Comoros"],
    ["175","Mayotte"],
    ["178","Congo"],
    ["180","Dem. Rep. of the Congo"],
    ["184","Cook Isds"],
    ["188","Costa Rica"],
    ["191","Croatia"],
    ["192","Cuba"],
    ["196","Cyprus"],
    ["200","Czechoslovakia"],
    ["203","Czech Rep."],
    ["204","Benin"],
    ["208","Denmark"],
    ["212","Dominica"],
    ["214","Dominican Rep."],
    ["218","Ecuador"],
    ["222","El Salvador"],
    ["226","Equatorial Guinea"],
    ["231","Ethiopia"],
    ["232","Eritrea"],
    ["233","Estonia"],
    ["234","Faeroe Isds"],
    ["238","Falkland Isds (Malvinas)"],
    ["239","South Georgia and the South Sandwich Islands"],
    ["242","Fiji"],
    ["246","Finland"],
    ["251","France"],
    ["254","French Guiana"],
    ["258","French Polynesia"],
    ["260","Fr. South Antarctic Terr."],
    ["262","Djibouti"],
    ["266","Gabon"],
    ["268","Georgia"],
    ["270","Gambia"],
    ["275","State of Palestine"],
    ["276","Germany"],
    ["288","Ghana"],
    ["292","Gibraltar"],
    ["296","Kiribati"],
    ["300","Greece"],
    ["304","Greenland"],
    ["308","Grenada"],
    ["312","Guadeloupe"],
    ["316","Guam"],
    ["320","Guatemala"],
    ["324","Guinea"],
    ["328","Guyana"],
    ["332","Haiti"],
    ["334","Heard Island and McDonald Islands"],
    ["336","Holy See (Vatican City State)"],
    ["340","Honduras"],
    ["344","China, Hong Kong SAR"],
    ["348","Hungary"],
    ["352","Iceland"],
    ["360","Indonesia"],
    ["364","Iran"],
    ["368","Iraq"],
    ["372","Ireland"],
    ["376","Israel"],
    ["381","Italy"],
    ["384","CÃ´te d'Ivoire"],
    ["388","Jamaica"],
    ["392","Japan"],
    ["398","Kazakhstan"],
    ["400","Jordan"],
    ["404","Kenya"],
    ["408","Dem. People's Rep. of Korea"],
    ["410","Rep. of Korea"],
    ["414","Kuwait"],
    ["417","Kyrgyzstan"],
    ["418","Lao People's Dem. Rep."],
    ["422","Lebanon"],
    ["426","Lesotho"],
    ["428","Latvia"],
    ["430","Liberia"],
    ["434","Libya"],
    ["440","Lithuania"],
    ["442","Luxembourg"],
    ["446","China, Macao SAR"],
    ["450","Madagascar"],
    ["454","Malawi"],
    ["457","Sarawak"],
    ["458","Malaysia"],
    ["459","Peninsula Malaysia"],
    ["461","Sabah"],
    ["462","Maldives"],
    ["466","Mali"],
    ["470","Malta"],
    ["474","Martinique"],
    ["478","Mauritania"],
    ["480","Mauritius"],
    ["484","Mexico"],
    ["496","Mongolia"],
    ["498","Rep. of Moldova"],
    ["499","Montenegro"],
    ["500","Montserrat"],
    ["504","Morocco"],
    ["508","Mozambique"],
    ["512","Oman"],
    ["516","Namibia"],
    ["520","Nauru"],
    ["524","Nepal"],
    ["528","Netherlands"],
    ["530","Neth. Antilles"],
    ["532","Neth. Antilles and Aruba"],
    ["533","Aruba"],
    ["534","Saint Maarten"],
    ["535","Bonaire"],
    ["540","New Caledonia"],
    ["548","Vanuatu"],
    ["554","New Zealand"],
    ["558","Nicaragua"],
    ["562","Niger"],
    ["566","Nigeria"],
    ["570","Niue"],
    ["574","Norfolk Isds"],
    ["579","Norway"],
    ["580","N. Mariana Isds"],
    ["581","United States Minor Outlying Islands"],
    ["583","FS Micronesia"],
    ["584","Marshall Isds"],
    ["585","Palau"],
    ["586","Pakistan"],
    ["588","East and West Pakistan"],
    ["591","Panama"],
    ["598","Papua New Guinea"],
    ["600","Paraguay"],
    ["604","Peru"],
    ["608","Philippines"],
    ["612","Pitcairn"],
    ["616","Poland"],
    ["620","Portugal"],
    ["624","Guinea-Bissau"],
    ["626","Timor-Leste"],
    ["634","Qatar"],
    ["642","Romania"],
    ["643","Russian Federation"],
    ["646","Rwanda"],
    ["647","Ryukyu Isd"],
    ["654","Saint Helena"],
    ["658","Saint Kitts, Nevis and Anguilla"],
    ["659","Saint Kitts and Nevis"],
    ["660","Anguilla"],
    ["662","Saint Lucia"],
    ["666","Saint Pierre and Miquelon"],
    ["670","Saint Vincent and the Grenadines"],
    ["674","San Marino"],
    ["678","Sao Tome and Principe"],
    ["682","Saudi Arabia"],
    ["686","Senegal"],
    ["688","Serbia"],
    ["690","Seychelles"],
    ["694","Sierra Leone"],
    ["698","Sikkim"],
    ["699","India"],
    ["702","Singapore"],
    ["703","Slovakia"],
    ["704","Viet Nam"],
    ["705","Slovenia"],
    ["706","Somalia"],
    ["710","South Africa"],
    ["716","Zimbabwe"],
    ["724","Spain"],
    ["728","South Sudan"],
    ["729","Sudan"],
    ["732","Western Sahara"],
    ["740","Suriname"],
    ["748","Swaziland"],
    ["752","Sweden"],
    ["757","Switzerland"],
    ["760","Syria"],
    ["762","Tajikistan"],
    ["764","Thailand"],
    ["768","Togo"],
    ["772","Tokelau"],
    ["776","Tonga"],
    ["780","Trinidad and Tobago"],
    ["784","United Arab Emirates"],
    ["788","Tunisia"],
    ["792","Turkey"],
    ["795","Turkmenistan"],
    ["796","Turks and Caicos Isds"],
    ["798","Tuvalu"],
    ["800","Uganda"],
    ["804","Ukraine"],
    ["807","TFYR of Macedonia"],
    ["818","Egypt"],
    ["826","United Kingdom"],
    ["834","United Rep. of Tanzania"],
    ["837","Bunkers"],
    ["842","USA"],
    ["850","US Virgin Isds"],
    ["854","Burkina Faso"],
    ["858","Uruguay"],
    ["860","Uzbekistan"],
    ["862","Venezuela"],
    ["876","Wallis and Futuna Isds"],
    ["882","Samoa"],
    ["887","Yemen"],
    ["891","Serbia and Montenegro"],
    ["894","Zambia"]
]

Commodity_List.each do |code, name|
  Commodity.create( name: name, code: code )
end


Country_List.each do |code, name|
  Country.create( name: name, code: code)
end